### ISSUE TITLE
Expose DraftLog instance's line on stdout stream

### ISSUE THREAD

**Issue by datitisev** [ivanseidel/node-draftlog#2]
It may be useful to expose the line number whenever you update a draft console via `console.draft()()` so if we want to clear that line, we can use the line number without adding complex code to calculate it ourselves, as I see `DraftLog._line` contains the line, however it cannot be accessed via `console.draft()()._line` as `console.draft()` returns an `new DraftLog(...).update`.

Maybe you could add this simple thing by returning `this._line` in the `update` method.
Sorry about the big sentence above, I didn't know how to explain myself.

Or maybe a feature to clean the line completely could be added, as
```js
DraftLog.update(); # or DraftLog.update('');
```
still leaves an empty line.

Thank you for your time, and sorry if this isn't something you want DraftLog to do.
Thanks for making such a great module. ✌️

**Comment by ivanseidel** [comment]
Hi @datitisev, Glad you liked DraftLog!

You can simply clear it by calling the update method without params:

```javascript
var draft = console.draft('Hello you!')

setTimeout(function (){
  // Clear the line
  draft()
}, 500)
```

Can you please elaborate on the reasons why you want access to a line?

**Comment by datitisev** [comment]
Thank you for such a quick response, @ivanseidel 
I want access to the line because I have a script that clears it.
What I want to be able to do easily is, once I'm finished using the Draft with a progress bar (aka once the progress bar finishes), the line gets cleared so the next log goes right under the log before where the Draft instance was.

Let me give you an example:
```
# Starting the example
$ node index

First log
[==           ] 24%

# After the progress bar finishes
$ node index

First log
Second log
Third log
```

I just realized that this can be done just by doing `DraftLog.update('Second log')`, however, my app has code distributed across files which would make me need to pass the DraftLog instance.
It may also contain 5 progress bars, however there may only be 2 logs afterwards.
I just want to be able to complete delete any trace of the DraftLog line as if nothing had happened.

I hope that makes sense... it did in my head until I started writing it 🙄 😛 

Thank you for your time. 😊

**Comment by ivanseidel** [comment]
Well, I wouldn't recommend changing the line by yourself because that's something the Library is solely responsible for.

However, your solution might be in using an nicer approach to the problem. You might make each function callback with it's own draftLog line updater, that will be passed to the next one.

Like this:

```javascript
// Sketch, not tested.

function makeStuffHappen(whereToLog, next){ 
  whereToLog('First Log');

  // Update log and call next
  whereToLog = console.draft('[=====       ]');
  next(whereToLog);
}
```

That will do what you want, but without delays.

Closing the Issue, but fell free to continue discussion if you need ;)

**Comment by datitisev** [comment]
Ok, thanks for the fast example.
I just thought that maybe clearing the line completely would be beneficial for this library (and me 😉 )

Thank you for your time.
Have a nice day!

**Comment by ivanseidel** [comment]
Oh, by the way...
It is not possible to completely "clear" a line from the console. The only thing we can do, is clear it's content, but the line will still exist empty after that...

That's because of the way terminal works =/

Have a nice day too!

**Comment by HaykoKoryun** [comment]
@ivanseidel I think this feature needs to be reopened as your suggestion might not work in all situations. Take this small example I simplified from another project (where I was downloading upwards of 200 parts of a video from a streaming server with a download queue of 20); reusing a draft instance would be a bit convoluted and confusing to the user:

```javascript
require('draftlog').into(console)

for(var i = 0; i < 20; ++i)
{
	(function(i)
	{
		var label = "reticulating spline #" + i + ": ";
		var progress = 0;
		var max = Math.ceil(Math.random() * 100);
		
		var log = console.draft();
		
		function update()
		{
			progress += Math.round(Math.random() * 5);
			
			if(progress >= max)
			{
				log("\b");
			}
			else
			{
				log(label + Math.round(progress / max * 100) + "%");
				setTimeout(update, Math.random() * 2000);
			}
		}
		
		update();
	})(i);
}
```

Tasks all finish at random times and leave an empty line, now imagine that when a task complete another task it started, wouldn't it look weird to have that new task appear in the middle of the other tasks rather than at the bottom where new tasks should start?

**Comment by ivanseidel** [comment]
Let's go in parts, to explain the problem:

ANSI specification doesn't supports any "remove" specific lines as you want (Actually "removing" the line). That is NOT possible in ANY terminal, unless you re-write everything after it (clearing the whole screen, then writing it again).

Re-writing the texts after a draft to "remove" the line is not efficient, as we would need to record all the texts that were written, as well as update all draft's line after that point.

(Please, read the supported commands from: https://en.wikipedia.org/wiki/ANSI_escape_code)

Now, regarding the specific objective you want to achieve, I don't see any solution unless you try to re-write all the drafts just like rendering them again, and reordering for what purpose you need, so that there wouldn't be any spaces left.

The only supported feature to remove lines is:

`ED – Erase in Display`: `Clears part of the screen. If {\displaystyle n} n is 0 (or missing), clear from cursor to end of screen. If {\displaystyle n} n is 1, clear from cursor to beginning of the screen. If {\displaystyle n} n is 2, clear entire screen (and moves cursor to upper left on DOS ANSI.SYS). If {\displaystyle n} n is 3, clear entire screen and delete all lines saved in the scrollback buffer (this feature was added for xterm and is supported by other terminal applications).`

But, as you can see, no "specific" line is supported.

So, I don't see a way out for your problem, that is not code structured on top of DraftLog. Here, is my idea of how you could do that:

(Recording: https://asciinema.org/a/1syxen57qluac7onx5wexiske)

```javascript
require('.').into(console)

function ReusableDrafts(){
  this.drafts = []
}

ReusableDrafts.prototype.get = function(){
  var self = this
  var draft = this.drafts.find(d => !d.inUse)

  // Add new draft to list if not yet
  if (!draft){
    draft = console.draft();
    this.drafts.push(draft);
  }

  draft.inUse = true
  return function (){
    if (!arguments[0]){
      // Release draft
      draft.inUse = false
    }

    // Proxy to draft 
    draft.apply(draft, arguments);
  }
}

/*
 * Usage
 */
var reusable = new ReusableDrafts(10)

setInterval(() => {
  var draft = reusable.get()
  var i = 0;
  var interval = setInterval(() => {
    draft('[' + '='.repeat(++i) + ' '.repeat(10 - i) + ']')

    if (i >= 10) {
      draft()
      clearInterval(interval)
    }
  }, Math.random() * 200);
}, 100)
```

**Comment by datitisev** [comment]
@ivanseidel Interesting concept.
However, I do know there is some way to remove a line from the terminal using the `readline` module. I think it is an official module (like util).

I can't get the code right now, I will though in a few hours. But I can confirm that it deletes the line from the terminal, unless I am mistaken and looked at the wrong thing.

**Comment by ivanseidel** [comment]
What you are referring to is to "move the cursor". Yes, you can move the cursor position, but you still not able to remove the line. But you can write on top of it anyway...

It's like this:

```
1: Line 1
2: Line 2
3: Last Line|

// Issue a cursor up:
1: Line 1
2: Line 2  |
3: Last Line

// Issue a clear line command
// Issue a cursor up:
1: Line 1
2: |
3: Last Line

// Issue a Write
1: Line 1
2: hey there|
3: Last Line
```

But the line you were, will continue to exist... It doesn't delete the line. That's not possible.

**Comment by datitisev** [comment]
@ivanseidel Oh, I see. I guess I was referring to that, as I got the code that does that from Yarn's repo 😛 (`clearNthLine`)

**Comment by HaykoKoryun** [comment]
@ivanseidel I think we're on the right track

The way I imagine it working is this, once a `draft` is no longer needed, it gets discarded so the next `draft` in sequence starts writing on the previous line that belonged to the one that go discarded.

Even if it's not possible to delete a line, e.g. once you've started writing on line 20, you can't get rid of the line, it will still work in my use case and others' when they have a fixed number of lines they need.

**Comment by ivanseidel** [comment]
That is a specific purpose, that something like what I wrote (`ReusableDrafts`) would be great for it.

However, the default behavior being to 'get the oldest log line and update' is not good, because one of the premisses I think people should have when using the library is: `console.draft()` logs at the end, just like `console.log()`. Imagine the mess a log file could become, if we chose the line in witch to put the log.. 

And still, even after stopping updating a log line, doesn't means it can be updated by any draft. We still want to persist that "last" state.

In your case, you should probably get something like the `ReusableLogs` working. It will be just perfect I think =)

If you guys have anything else to add or ask, I'm happy to answer it. but will close this issue for now.

Thanks!

**Comment by HaykoKoryun** [comment]
I got something nice working with very minimal modifications 🕺 
https://asciinema.org/a/99n479wbk6uh18xkhi3qoxi7y
![draft-demo](https://cloud.githubusercontent.com/assets/2579764/24018309/c4c02e5c-0aac-11e7-8fda-149464b58d69.gif)
