### ISSUE TITLE
Question: Fix line at the bottom

### ISSUE THREAD

**Issue by sirgallifrey** [ivanseidel/node-draftlog#3]
First of all: Nice lib!

Now my question: Is it possible to fix a log at the bottom while I keep sending more console.logs?

I want to keep a status bar counting the number of downloads and failed downloads, while I keep submitting lines with the individual downloads

**Comment by ivanseidel** [comment]
Hey @sirgallifrey! Thanks!

Well, that's not possible with DraftLog. That can mess a lot with the Terminal, because you would have to keep track of the lines being output (I think so).

You might accomplish that with manual ANSI codes, or maybe another library that updates just the last line of code in the terminal.

Maybe changing the UI to fit DraftLog will do it

**Comment by sirgallifrey** [comment]
Thx @ivanseidel! I'll keep going without this for now, it would be a little overkill anyways.. haha thanks again!
